service: awsLayer-tmdbsimple

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: ${opt:stage, 'prod'}

layers:
  tmdbsimple:
    name: tmdbsimple
    path: tmdbsimple/
    description: python wrapper for the The Moview Database (TMDb) API v3. For more info., https://github.com/celiao/tmdbsimple/
    compatibleRuntimes:
      - python3.8